// CHỖ NÀY THỰC HIỆN VIỆC ĐỊNH NGHĨA CÁC LOẠI MÃ LỖI Ở ĐÂY. 

export const ERROR_CODES = {
    REQUIRED_FIELD: "USERNAME_OR_PASSWORD_REQUIRED",
    INVALID_INPUT_FORMAT: "INVALID_INPUT_FORMAT",
    INVALID_FIELD: "INVALID_USERNAME_OR_PASSWORD",
    UNKNOW_ERROR: "UNKNOW_ERROR",
    SERVER_ERROR: "SERVER_ERROR",
    DB_ERROR: "DB_ERROR"
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
