// CHỖ NÀY THỰC HIỆN VIỆC ĐỊNH NGHĨA CÁC LOẠI MÃ LỖI Ở ĐÂY. 

export const ERROR_CODES = {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USERNAME_REQUIRED: "USERNAME_REQUIRED",
    PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
    INVALID_USERNAME: "INVALID_USERNAME",
    INVALID_PASSWORD: "INVALID_PASSWORD",
    UNKNOW_ERROR: "UNKNOW_ERROR",
    SERVER_ERROR: "SERVER_ERROR",
    DB_ERROR: "DB_ERROR"
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
