// CHỖ NÀY THỰC HIỆN VIỆC ĐỊNH NGHĨA CÁC LOẠI MÃ LỖI Ở ĐÂY. 

export const ERROR_CODES = {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USERNAME_REQUIRED: "USERNAME_REQUIRED",
    PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
    INVALID_USERNAME: "INVALID_USERNAME",
    INVALID_PASSWORD: "INVALID_PASSWORD",
    UNKNOW_ERROR: "UNKNOW_ERROR",
    DB_ERROR: "DB_ERROR"
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

// export const HTTP_STATUS_CODES = {
//     OK: 200,
//     CREATED: 201,
//     BAD_REQUEST: 400,
//     UNAUTHORIZED: 401,
//     NOT_FOUND: 404,
//     INTERNAL_SERVER_ERROR: 500
// } as const;

// export type HttpStatus = typeof HTTP_STATUS_CODES[keyof typeof HTTP_STATUS_CODES]; 