export const AUTH_ERROR_CODES = {
    REQUIRED_FIELD: "EMAIL_OR_PASSWORD_REQUIRED",
    INVALID_INPUT_FORMAT: "INVALID_INPUT_FORMAT",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    TOKEN_IS_WRONG: "TOKEN_IS_WRONG",
    TOKEN_EXPIRES: "TOKEN_EXPIRES"
} as const;
